### ISSUE TITLE
Getting MathLink to work on Mathematica 10 (on Fedora 22, in my case)

### ISSUE THREAD

**Issue by scyrusm** [JuliaInterop/MathLink.jl#2]
Is easy--all that needs to be changed is the value of mlib in low_level.jl.  In my case, I just set mlib="/usr/local/Wolfram/Mathematica/10.1/SystemFiles/Links/MathLink/DeveloperKit/Linux-x86-64/CompilerAdditions/libML64i4", and so far things work.  Just thought I'd let you know, since it's an easy fix, and there seem to be other users of Mathematica 10\* on linux who had the same issue.

**Comment by one-more-minute** [comment]
That's great to hear! If you have a moment to put a PR together, it'd be really cool to detect and implement this in the package.

**Comment by scyrusm** [comment]
I'll do this soon.

**Comment by simonbyrne** [comment]
this should hopefully work now.
