### ISSUE TITLE
Code fails in julia, but works in Mathematica

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JuliaInterop/MathLink.jl#23]
The following does fails in julia
```julia
function v_bud(m, nl, ns)
    W"Set"(W"nl",nl) |> weval
    W"Set"(W"ns",ns) |> weval
    W"Set"(W"mm",m ) |> weval
    W```
    v[n1_, n2_] := Module[{r1, r1s, r2, R1, R2},
       r2 = R1/(2 m R1 - 1);
       r1s = R1 /. Solve[n1 R1^2 + n2 r2^2 == 1, R1];
       r1 = r1s[[FirstPosition[r1s /. m -> Sqrt[n1 + n2],
            n_ /; n == 1/Sqrt[n1 + n2]]]] // Simplify;
       r2 = r2 /. R1 -> r1 // Simplify;
       n1 r1^3 + n2 (r2)^3
    ];
    Chop@(v[nl,ns]/.m->mm)[[1]]
    ``` |> weval
end # function
v_bud(5,2,1)
```
Running this in mathematica is fine: (same definition of `v`)
```mathematica
Chop@(v[2,1]/.m->5)[[1]]
```
I cannot really explain why, I thought it is the number type, but even converting everything to floats is fine in Mathematica (with warning) but picking the right solution fails in julia.

**Comment by simonbyrne** [comment]
It works for me (at least, it gives a very long answer). What are you getting/expecting?

**Comment by BeastyBlacksmith** [comment]
Ok, I worked that out. It was a mistake in my definition. Everything fine :)
