### ISSUE TITLE
How can I set the environment variables of JULIA_MATHKERNEL and JULIA_MATHLINK in linux?

### ISSUE THREAD

**Issue by xuyown** [JuliaInterop/MathLink.jl#37]
I have installed Mathematica,  and I also installed the MathLink.jl. But, When I typing "using MathLink" in Julia REPL gives the following error. How do I set it up?
![1](https://user-images.githubusercontent.com/50038846/78353500-bd746c00-75dc-11ea-9887-9dc991801adf.png)

**Comment by simonbyrne** [comment]
What version of Mathematica are you using?

**Comment by simonbyrne** [comment]
is `math` available in your terminal?

**Comment by simonbyrne** [comment]
To set an environment variable, typically you add something like this to your `~/.profile` file
```
export JULIA_MATHKERNEL=...

**Comment by xuyown** [comment]
> To set an environment variable, typically you add something like this to your `~/.profile` file
> 
> ```
> export JULIA_MATHKERNEL=...
> export JULIA_MATHLINK=...
> ```
> 
> You will then need to re-run `Pkg.build()`

Thanks for your reply.
My Mathematica version is 12.1.
I set the environment variable in Julia's startup in the picture.
![5](https://user-images.githubusercontent.com/50038846/78417009-57c9c380-7660-11ea-998e-54eb6c65fa35.png)
After re-run pkg.build, I can run it correctly.
Last, I have other questions, 
Is the environment variable of MATHKERNEL setting math or MathKernal? Because in the executable file of Mathematica, both math and MathKernal exist

**Comment by xuyown** [comment]
> To set an environment variable, typically you add something like this to your `~/.profile` file
> 
> ```
> export JULIA_MATHKERNEL=...
> export JULIA_MATHLINK=...
> ```
> 
> You will then need to re-run `Pkg.build()`

Thanks for your reply.
My Mathematica version is 12.1.
I set the environment variable in Julia's startup in the following picture.
![5](https://user-images.githubusercontent.com/50038846/78417027-9a8b9b80-7660-11ea-8b7f-557b91fcda55.png)
After re-run pkg.build, I can run it correctly.
Last, I have other questions,
Is the environment variable of MATHKERNEL setting math or MathKernal? Because in the executable file of Mathematica, both math and MathKernal exist.
![6](https://user-images.githubusercontent.com/50038846/78417048-c3139580-7660-11ea-94aa-9fd0466b57a6.png)

**Comment by simonbyrne** [comment]
I use `MathKernel`, but I believe either should work.

**Comment by xuyown** [comment]
Thank you, I get it.
