### ISSUE TITLE
Including overloading of basic algebra

### ISSUE THREAD

**Issue by fremling** [JuliaInterop/MathLink.jl#48]
Hi. Is there a particular reason why the library has chosen not to overload the basic arithmetic operator such as +,-,*,/?

Currently need to add some biolerpate code at the top to e able to things like 

x=W"x"
y=W"y"
z=x+y
w=x-y

-------

import Base.+
import Base.*
import Base.-
import Base./
+(a::MathLink.WSymbol,b::MathLink.WSymbol)=weval(W"Plus"(a,b))
+(a::MathLink.WExpr,b::MathLink.WSymbol)=weval(W"Plus"(a,b))
+(a::MathLink.WExpr,b::MathLink.WExpr)=weval(W"Plus"(a,b))
-(a::MathLink.WSymbol)=weval(W"Minus"(a))
-(a::MathLink.WExpr)=weval(W"Minus"(a))
-(a::MathLink.WSymbol,b::MathLink.WSymbol)=weval(W"Plus"(a,W"Minus"(b)))
-(a::MathLink.WExpr,b::MathLink.WSymbol)=weval(W"Plus"(a,W"Minus"(b)))
-(a::MathLink.WExpr,b::MathLink.WExpr)=weval(W"Plus"(a,W"Minus"(b)))
*(a::MathLink.WExpr,b::MathLink.WExpr)=weval(W"Times"(a,b))
*(a::MathLink.WSymbol,b::MathLink.WExpr)=weval(W"Times"(a,b))
*(a::MathLink.WExpr,b::MathLink.WSymbol)=weval(W"Times"(a,b))
*(a::MathLink.WSymbol,b::MathLink.WSymbol)=weval(W"Times"(a,b))
/(a::MathLink.WSymbol,b::MathLink.WSymbol)=weval(W"Times"(a, W"Power"(b, -1)))
/(a::MathLink.WExpr,b::Number)=weval(W"Times"(a, W"Power"(b, -1)))

**Comment by simonbyrne** [comment]
I was originally trying to keep this as a backend package, closely mirroring WSTP/MathLink itself, and build another package as the frontend, but never got around to that.

This would also result in eager evaluation, which would give different semantics from the underlying Wolfram language.

**Comment by fremling** [comment]
I see. I'm not an expert of the inner workings of mathematica, but I guess the , the `weval` could easily be dropped to avoid eager evaluation. 

For new users of the package however, having the most basic operations  +, -, *, / overloaded would still be quite useful and pedagogic.

**Comment by fremling** [comment]
After playing around with your package now for a while i have collected quite a bunch of  auxiliary functions that make sense to me.
I'm attaching the files here since i'm not very familiar with the pull request architecture (and I'm also not sure where you would want the functions).

The files contain overloading of functions +,-,*,/,^ as well as a switch  `MLGreedyEval` (default is false) to toggle greedy or delayed evluation.
There are also functions that augment the `put` function to handle julia fractions as well as complex numbers.

Further is there a function `W2Mstr that can translate the ML representation to a string that can be pasted directly into the mathematica editor (quite useful)

Further there is workaround that allows put to handle Int128 by performing a prime factorization (since it's currently not suported).

The functions also comes with some basic tests (see attachments in zip file).

I'd love to make this parts of the  package, so if there is anything i can do to help please  let me know.

[MathLinkHeaders.zip](https://github.com/JuliaInterop/MathLink.jl/files/7143572/MathLinkHeaders.zip)

**Comment by simonbyrne** [comment]
to be honest, my time is limited so that I really only have time to do bug fixes. Your best option might be to just create a new package (which is fairly simple in Julia), and add this as a dependency.

**Comment by simonbyrne** [comment]
Unless of course someone wants to take over maintenance.

**Comment by simonbyrne** [comment]
Yeah, you have to `Pkg.build()` it manually when using the source.

**Comment by fremling** [comment]
Ah, silly me. Now it works :)
I also created a PR for the update. I think we can close this issue now :)
