### ISSUE TITLE
Bug: Julia Mathlink installation on Windows 10

### ISSUE THREAD

**Issue by Shuvomoy** [JuliaInterop/MathLink.jl#49]
Hi I am trying to install MathLink.jl on Windows 10. I have a full version of Mathematica 12.3, but I do not think it contains any "libML64.dll/ libML32.dll" file as mentioned in the installation package. The closest is `ml64i4.dll` located in `C:\Program Files\Wolfram Research\Mathematica\12.3\SystemFiles\Links\MathLink\DeveloperKit\Windows-x86-64\SystemAdditions` and I set this folder as `MathLink dynamic library`. However, after installation when I run `using MathLink`, I get the error `InitError: could not load library "C:\Program Files\Wolfram Research\Mathematica\12.3\SystemFiles\Links\MathLink\DeveloperKit\Windows-x86-64\SystemAdditions"`.

**Comment by simonbyrne** [comment]
The README looks a bit out of date, we do search for that file (see `deps/build.jl`):
https://github.com/JuliaInterop/MathLink.jl/blob/master/deps/build.jl#L76-L78

What happens if you run that file manually (without the environment variables being set)

**Comment by fremling** [comment]
Hi @Shuvomoy,
Did you ever get MathLink.jl working on Windows 10 or is there still and issue?

**Comment by Shuvomoy** [comment]
@fremling Actually I switched to MacOS subsequently, so I never tested if MathLink.jl works on Windows 10...

**Comment by fremling** [comment]
Then I will close this issue for now
