### ISSUE TITLE
Problem : UndefVarError: set_texOutput not defined

### ISSUE THREAD

**Issue by mnemosyne-xx** [JuliaInterop/MathLink.jl#61]
there's a problem with MathLink.set_texOutput(false) | (or true)

--> 
julia> using MathLink
julia> MathLink.set_texOutput(false)
ERROR: UndefVarError: set_texOutput not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base ./Base.jl:31
 [2] top-level scope
   @ REPL[2]:1

**Comment by fremling** [comment]
Hi @mnemosyne-xx 
The problem he was simply that the set_texOutput functionality had not been merged into the main Julia repository. Try updating to version 0.5.0 as see if the problem persists.

**Comment by fremling** [comment]
As I believe the problem should be fixed in v0.5.0 i will close this ticket.
