### ISSUE TITLE
ParseError: KaTeX parse error

### ISSUE THREAD

**Issue by mnemosyne-xx** [JuliaInterop/MathLink.jl#62]
Another problem with GeoPosition (for example).. Thx a lot for a soluce...

coucher = W```
Sunrise[GeoPosition[{48.41, -6.11}], DateObject[{2022,9, 8, 0, 0}]]
``` |> weval 

--->  ParseError: KaTeX parse error: Unexpected end of input in a macro argument, expected '}' at end of input: \fbox{\text{Minute: }\text{Thu 8 Sep 2022 07:51}\text{GMT}+2$}$

**Comment by fremling** [comment]
Hi @mnemosyne-xx 
I don't seem to be able to reproduce your error...

If i call the function the "normal" way everything work fine for me. 

    julia> weval(W`Sunrise[GeoPosition[{48.41, -6.11}], DateObject[{2022,9, 8, 0, 0}]]`)

    W"DateObject"(W"List"(2022, 9, 8, 7, 51), "Minute", "Gregorian", 2.0)

Also doing it your way seems to work for me. 
    julia> coucher = W```
           Sunrise[GeoPosition[{48.41, -6.11}], DateObject[{2022,9, 8, 0, 0}]]
           ```
    W"Sunrise"(W"GeoPosition"(W"List"(48.41, -6.11)), W"DateObject"(W"List"(2022, 9, 8, 0, 0)))

    julia> weval(coucher)
    W"DateObject"(W"List"(2022, 9, 8, 7, 51), "Minute", "Gregorian", 2.0)

**Comment by mnemosyne-xx** [comment]
It seems OK with new version of VSCode 1.71.2 ...
     Thx a lot
