### ISSUE TITLE
MathLink package can't find file "dep.jl"  & fail to precompiling pkg.

### ISSUE THREAD

**Issue by sesameman** [JuliaInterop/MathLink.jl#63]
error msg
```Julia
[ Info: Precompiling MathLink [18c93696-a329-5786-9845-8443133fa0b4]
ERROR: LoadError: SystemError: opening file "/Users/ /.julia/packages/MathLink/r23jC/deps/deps.jl": No such file or directory
Stacktrace:
  [1] systemerror(p::String, errno::Int32; extrainfo::Nothing)
    @ Base ./error.jl:176
  [2] #systemerror#80
    @ ./error.jl:175 [inlined]
  [3] systemerror
    @ ./error.jl:175 [inlined]
  [4] open(fname::String; lock::Bool, read::Nothing, write::Nothing, create::Nothing, truncate::Nothing, append::Nothing)
    @ Base ./iostream.jl:293
  [5] open
    @ ./iostream.jl:275 [inlined]
  [6] open(f::Base.var"#387#388"{String}, args::String; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./io.jl:382
  [7] open
    @ ./io.jl:381 [inlined]
  [8] read
    @ ./io.jl:462 [inlined]
  [9] _include(mapexpr::Function, mod::Module, _path::String)
    @ Base ./loading.jl:1484
 [10] include(mod::Module, _path::String)
    @ Base ./Base.jl:419
 [11] include(x::String)
    @ MathLink ~/.julia/packages/MathLink/r23jC/src/MathLink.jl:1
 [12] top-level scope
    @ ~/.julia/packages/MathLink/r23jC/src/MathLink.jl:7
 [13] include
    @ ./Base.jl:419 [inlined]
 [14] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base ./loading.jl:1554
 [15] top-level scope
    @ stdin:1
in expression starting at /Users/ /.julia/packages/MathLink/r23jC/src/MathLink.jl:1
in expression starting at stdin:1
ERROR: LoadError: Failed to precompile MathLink [18c93696-a329-5786-9845-8443133fa0b4] to /Users/kangjiayin/.julia/compiled/v1.8/MathLink/jl_Y2Dvgx.
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base ./loading.jl:1705
  [3] compilecache
    @ ./loading.jl:1649 [inlined]
  [4] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1337
  [5] _require_prelocked(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1200
  [6] macro expansion
    @ ./loading.jl:1180 [inlined]
  [7] macro expansion
    @ ./lock.jl:223 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1144
  [9] include(fname::String)
    @ Base.MainInclude ./client.jl:476
 [10] top-level scope
    @ ~/Desktop/program/julia/DSE_BSEt/src/readmeson.jl:14
```
Julia v v1.8
mathlink [18c93696] MathLink v0.5.0

**Comment by fremling** [comment]
Hi!
What is going on here is that the preinstalation of MathLink did not work. This is usually the case if it cannot find Mathematica. Do you have mathematica installed on your system?

I agree that the error message is not very instructive, and should be improved...

**Comment by sesameman** [comment]
> 
thank you for your reply.
There is no Mathematica when i installed math link. There was a error massage told me to install Mathematica.
But after that I installed Mathematica, And reinstalled mathlink.

here goes the error massage above. 

Could you please tell me how to fix it? or any suggestions?

**Comment by sesameman** [comment]
> 

thank you for your reply.
There is no Mathematica when i installed math link. There was a error massage told me to install Mathematica.
But after that I installed Mathematica, And reinstalled mathlink.

here goes the error massage above.

Could you please tell me how to fix it? or any suggestions?

**Comment by sesameman** [comment]
> Hi! What is going on here is that the preinstalation of MathLink did not work. This is usually the case if it cannot find Mathematica. Do you have mathematica installed on your system?
> 
> I agree that the error message is not very instructive, and should be improved...
thank you for your reply.
There is no Mathematica when i installed math link. There was a error massage told me to install Mathematica.
But after that I installed Mathematica, And reinstalled mathlink.

here goes the error massage above.

Could you please tell me how to fix it? or any suggestions?

**Comment by fremling** [comment]
If you now have Mathematica installed, the easiest way to proceed it to reinstall MathLink (by first removing it).
If this still does not work where is a manual workaround.

Deep inside your julia build there is a folder called
/.julia/packages/MathLink/<version dependend>/deps

Make sure there is a file there called deps.jl with a link to the Mathematica installation. On my mashine it looks like this:

"
const mlib = "/usr/local/Wolfram/Mathematica/11.3/SystemFiles/Links/MathLink/DeveloperKit/Linux-x86-64/CompilerAdditions/libML64i4"
const mker = "WolframKernel"
"

(A patch is also on the way to make this clearer for the user, but it might take a while before it makes it to launch)

**Comment by fremling** [comment]
I added some of this information to the readme:

https://github.com/JuliaInterop/MathLink.jl/blob/master/README.md#installation-troubleshoot

**Comment by sesameman** [comment]
> 



> If you now have Mathematica installed, the easiest way to proceed it to reinstall MathLink (by first removing it). If this still does not work where is a manual workaround.
> 
> Deep inside your julia build there is a folder called /.julia/packages/MathLink//deps
> 
> Make sure there is a file there called deps.jl with a link to the Mathematica installation. On my mashine it looks like this:
> 
> " const mlib = "/usr/local/Wolfram/Mathematica/11.3/SystemFiles/Links/MathLink/DeveloperKit/Linux-x86-64/CompilerAdditions/libML64i4" const mker = "WolframKernel" "
> 
> (A patch is also on the way to make this clearer for the user, but it might take a while before it makes it to launch)

Thank you so much! 
I can't find my `dep.jl` file. So I removed `.Julia/packages/MathLink` before I reinstalled MathLink. Now everything is OK.
