### ISSUE TITLE
MathLink with HypergeometricFunctions

### ISSUE THREAD

**Issue by Li-shiyue** [JuliaInterop/MathLink.jl#73]
using MathLink
a=weval(W"Series"(HypergeometricFunctions.pFq((2,), (0.2,),W"z"),(W"z",-1,50)))
Closest candidates are:
  (::Type{T})(!Matched::AbstractChar) where T<:Union{AbstractChar, Number}
   @ Base char.jl:50
  (::Type{T})(!Matched::Base.TwicePrecision) where T<:Number
   @ Base twiceprecision.jl:266
  (::Type{T})(!Matched::Complex) where T<:Real
   @ Base complex.jl:44
  ...

**Comment by fremling** [comment]
Hi.  The code as you type will have no chance of working because the `HypergeometricFunctions` is not a defined function within MathLink.  What would be the corresponding Mathematica code that you would run in this instance?

**Comment by Li-shiyue** [comment]
> Hi. The code as you type will have no chance of working because the `HypergeometricFunctions` is not a defined function within MathLink. What would be the corresponding Mathematica code that you would run in this instance?
> 
> Or is there some other Julia library also at work in this example?

I also used HypergeometricFunctions in Julia
the Full code is
using MathLink
using HypergeometricFunctions
a=weval(W"Series"(HypergeometricFunctions.pFq((2,), (0.2,),W"z"),(W"z",-1,50)))

**Comment by fremling** [comment]
Hi. Your problem is that the `HypergeometricFunctions`package does no accept MathLink arguments. 

using MathLink
using HypergeometricFunctions

julia> HypergeometricFunctions.pFq((2,), (0.2,),1)
35.11151422002346

julia> HypergeometricFunctions.pFq((2,), (0.2,),W"z")
ERROR: MethodError: no method matching AbstractFloat(::MathLink.WSymbol)


If you want to use the Mathematica hypergeoemtric functions your need to use the HypergeometricPFQ function wich is builtin to Mathematica.

**Comment by Li-shiyue** [comment]
How can I define HypergeometirvPFQ in julia,while I see connection between Julia and mathematic through a char "W"

**Comment by fremling** [comment]
The syntac change is usually simple. Replace any Matematica function `<fun>` with `W"<fun>"` and the `[<arg>]` with `(<arg>)`. If you are unsure what it should look like you can always use the ' construction as

    W`<fun>`

Here follows a series of eamples of how to works figures out the correct syntax

Test that numerics values work

    julia> weval(W`HypergeometricPFQ[{1, 1}, {3, 3, 3}, 2.]`)
    1.0789344020671878

Test that algebraic expressions work

    julia> weval(W`HypergeometricPFQ[{1, 1}, {3, 3, 3}, z]`)
    W"HypergeometricPFQ"(W"List"(1, 1), W"List"(3, 3, 3), W"z")

Note that the `weval` is not nencarry. Mathlink does the translation anyway:

    julia> W`HypergeometricPFQ[{1, 1}, {3, 3, 3}, z]`
    W"HypergeometricPFQ"(W"List"(1, 1), W"List"(3, 3, 3), W"z")

Here the same thing with `weval`

    julia> weval(W"HypergeometricPFQ"([1, 1],[3, 3, 3], W"z"))
    W"HypergeometricPFQ"(W"List"(1, 1), W"List"(3, 3, 3), W"z")

And if you run the series you will get more data back:

    julia> weval(W"Series"(W"HypergeometricPFQ"([1, 1],[3, 3, 3], W"z"),(W"z",-1,2)))
    W"SeriesData"(W"z", -1, W"List"(W"HypergeometricPFQ"(W"List"(1, 1), W"List"(3, 3, 3), -1), W"Plus"(-8, W"Times"(8, W"HypergeometricPFQ"(W"List"(1, 1), W"List"(2, 2, 2), -1)), W"HypergeometricPFQ"(W"List"(1, 1), W"List"(3, 3, 3), -1)), W"Plus"(-16, W"Times"(4, W"BesselJ"(0, 2)), W"Times"(16, W"HypergeometricPFQ"(W"List"(1, 1), W"List"(2, 2, 2), -1)), W"HypergeometricPFQ"(W"List"(1, 1), W"List"(3, 3, 3), -1))), 0, 3, 1)


I hope this clarifies things.

**Comment by Li-shiyue** [comment]
Thanks! That helps a lot,I am not familiar with MathLink,I tried the method above and successfully get the result.
My goal is get the TaylorSeries coefficients, how can I access W"List"(-2.0401353687919177, 1.6538235838749207, 0.9454567962158056, 0.33340658574157367, 0.08626703289712206, 0.017680673659342557) the coefficient as I understand it?here is my code
a=weval(W"Series"(W"Hypergeometric1F1"(0.1,0.02, W"z"),(W"z",-1,5)))
W"SeriesData"(W"z", -1, W"List"(-2.0401353687919177, 1.6538235838749207, 0.9454567962158056, 0.33340658574157367, 0.08626703289712206, 0.017680673659342557), 0, 6, 1)

**Comment by fremling** [comment]
Hi @Li-shiyue, you can access the series data by looking at the `args` of `a`. The trick is to access the third argument which i a `W"List"`. We then access the arguments of the list to get the coefficients we want. 

    julia> a=weval(W"Series"(W"Hypergeometric1F1"(0.1,0.02, W"z"),(W"z",-1,5)))
    W`SeriesData[z, -1, List[-2.0401353687919177, 1.6538235838749207, 0.9454567962158056, 0.33340658574157367, 0.08626703289712206, 0.017680673659342557], 0, 6, 1]`
    julia> series =a.args[3].args
    6-element Vector{Float64}:
     -2.0401353687919177
      1.6538235838749207
      0.9454567962158056
      0.33340658574157367
      0.08626703289712206
      0.017680673659342557
