### ISSUE TITLE
precision may be lost

### ISSUE THREAD

**Issue by Li-shiyue** [JuliaInterop/MathLink.jl#79]
When I tried to use mathlink to get hypergeometircfunction's taylorSeries and uesed it to optimize ,it got warning.
The precision issue indeed influnce my experinement,How can I solve it?
Warning: General::munfl:
│    Exp[-999.803] is too small to represent as a normalized machine number;
│      precision may be lost.

**Comment by fremling** [comment]
Hi,
I'm not sure I see the problem. In Mathematica running `Exp[-999.803]` will return `0.0` and a warning that the precision is lost. 
![image](https://github.com/JuliaInterop/MathLink.jl/assets/13849332/161d89e1-73ef-4c47-a42f-6ce1ae708f75)

The `MathLink` code simply repeats this message but still delivers the answer.

    julia> A = weval(W`Exp[-999.803]`)
    ┌ Warning: General::munfl: 
    │    Exp[-999.803] is too small to represent as a normalized machine number;
    │      precision may be lost.
    └ @ MathLink ~/.julia/packages/MathLink/Ehhv0/src/eval.jl:16
    0.0
    julia> A
    0.0


What do you think should happen?

**Comment by Li-shiyue** [comment]
I see.now I know the problem,Thanks

**Comment by fremling** [comment]
Then i think we will close this issue
