### ISSUE TITLE
Mathematica arm64 version needed on M1 MacBook?

### ISSUE THREAD

**Issue by JanLeppert** [JuliaInterop/MathLink.jl#84]
I tried to use MathLink on MacBook with a M1 and I use Mathematica 12.3, which is a x86 (64bit) version and I get the following error:

ERROR: InitError: could not load library "/Applications/Mathematica.app/Contents/Frameworks/mathlink.framework/mathlink"
dlopen(/Applications/Mathematica.app/Contents/Frameworks/mathlink.framework/mathlink, 0x0001): tried: '/Applications/Mathematica.app/Contents/Frameworks/mathlink.framework/mathlink' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Mathematica.app/Contents/Frameworks/mathlink.framework/mathlink' (no such file), '/Applications/Mathematica.app/Contents/Frameworks/mathlink.framework/mathlink' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Library/Frameworks/mathlink.framework/mathlink' (no such file), '/System/Library/Frameworks/mathlink.framework/mathlink' (no such file, not in dyld cache), '/Applications/Mathematica.app/Contents/Frameworks/mathlink.framework/Versions/4/mathlink' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Mathematica.app/Contents/Frameworks/mathlink.framework/Versions/4/mathlink' (no such file), '/Applications/Mathematica.app/Contents/Frameworks/mathlink.framework/Versions/4/mathlink' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Library/Frameworks/mathlink.framework/Versions/4/mathlink' (no such file), '/System/Library/Frameworks/mathlink.framework/Versions/4/mathlink' (no such file, not in dyld cache)

Is it possible to use the x86_64 version of Mathematica with MathLink on a arm64 Mac or do I have to update Mathematica?

**Comment by JanLeppert** [comment]
Thanks for the suggestion @fremling,

but what is the correct file for the MathLink dynamic library on MacOS? I cannot find any of the suggested files from the Readme (libML64i4.so/ libML32i4.so on Linux or ml64i4.dll/ml32i4.dll/libML64.dll/ libML32.dll on Windows). I also followed the link from the example for the `deps.jl` file and found the similar path on my system:
`/Applications/Mathematica.app/Contents/SystemFiles/Links/MathLink/DeveloperKit/MacOSX-x86-64/CompilerAdditions` 
In this path there is a file `libMLi4.a` and I tried to link to this file, but with no sucess.

**Comment by fremling** [comment]
I must admit Mac is not my specialty: @simonbyrne do you know how Mathematica is set up on a Mac?

**Comment by simonbyrne** [comment]
What does
```
file /Applications/Mathematica.app/Contents/Frameworks/mathlink.framework/mathlink
```
give? On my machine, I get:
```
/Applications/Mathematica.app/Contents/Frameworks/mathlink.framework/mathlink: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [arm64]
/Applications/Mathematica.app/Contents/Frameworks/mathlink.framework/mathlink (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
/Applications/Mathematica.app/Contents/Frameworks/mathlink.framework/mathlink (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
```

**Comment by JanLeppert** [comment]
I only get one line with the x86_64 version:
```
/Applications/Mathematica.app/Contents/Frameworks/mathlink.framework/mathlink: Mach-O 64-bit dynamically linked shared library x86_64
```

**Comment by simonbyrne** [comment]
Can you download a newer version which supports ARM? If not, then you should be able to use it with the Julia x86 binaries.

**Comment by JanLeppert** [comment]
Thanks @simonbyrne 

I was able to update Mathematica to a newer version, which also supports ARM. With this I was able to use MathLink. 

So the answer to my question would be, that you need the ARM version of Mathematica for a Mac with M1 processor.

**Comment by simonbyrne** [comment]
You need the platform to be the same for both Julia and Mathematica (you should be able to in both x86 under Rosetta)
